name: soundpool
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 1.1.3
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  soundpool_platform_interface:
    git:
      url: https://github.com/fleoparra/soundpool_platform_interface.git
      ref: master
      path: soundpool_platform_interface
  
  soundpool_web:
    git:
      url: https://github.com/fleoparra/soundpool_web.git
      ref: master
      path: soundpool_web
 
  soundpool_macos:
    git:
      url: https://github.com/fleoparra/soundpool_macos.git
      ref: master
      path: soundpool_macos
    
    
flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.soundpool
        pluginClass: SoundpoolPlugin
      ios:
        pluginClass: SoundpoolPlugin
      web:
        default_package: soundpool_web 
      macos:
        default_package: soundpool_macos
